server:
  port: 8086

spring:
  application:
    name: el-aparato-avalos
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/el-aparato-avalos