server:
  port: 8086

spring:
  application:
    name: el-aparato-cliente
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    password: root
    username: root
    initialization-mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/el-aparato-avalos